# Generated by Django 5.0.1 on 2024-01-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_name', models.CharField(max_length=100)),
                ('redirect_path', models.CharField(max_length=200)),
            ],
        ),
    ]
